name: Action on Pull Reqest to run deploy of api config

on:
  push:
    tags:
      - main
  pull_request:
    branches:
      - main
jobs:
  deck-sync:
    runs-on: ubuntu-latest
    steps:
      - name: setup decK
        uses: kong/setup-deck@v1
        with:
          deck-version: "1.11.0"
      - name: clone repo
        uses: actions/checkout@v2
      - name: Run decK deck-sync
        env:
          DECK-EMAIL: ${{ secrets.DECK_EMAIL }}
          DECK-PASS: ${{ secrets.DECK_PASS }}
        run: deck konnect ping --konnect-email $DECK-EMAIL --konnect-password $DECK-PASS