name: decK action to deploy of api config using Konnect

on:
  push:
    branches:
      - main
jobs:
  deck-diff:
    runs-on: ubuntu-latest
    steps:
      - name: setup decK
        uses: kong/setup-deck@v1
        with:
          deck-version: "1.29.2"
      - name: clone repo
        uses: actions/checkout@v2
      - name: Run decK ping and diff
        env:
          DECK_KONNECT_TOKEN: ${{ secrets.DECK_PAT }}
        run: |
          deck gateway ping --konnect-control-plane-name="apiops-demo"
          cat ./src/main/resources/spec/conference-api-v1.0.yaml| deck file openapi2kong > ./konnect/kong.yaml
          cd ./konnect
          deck diff --konnect-control-plane-name="apiops-demo"

  deck-sync:
    needs: deck-diff
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: setup decK
        uses: kong/setup-deck@v1
        with:
          deck-version: "1.29.2"
      - name: clone repo
        uses: actions/checkout@v2
      - name: Run decK deck-sync
        env:
          DECK_KONNECT_TOKEN: ${{ secrets.DECK_PAT }}
        run: |
          deck sync