name: Build app image and push to Docker Hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  quotes-service:
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    
    name: Build (jar and docker) API DevOps (APIOps) Demo App
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'liberica'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build Docker Image AMD64
        run: ./gradlew bootBuildImage --imageName gamussa/apiops-workshop:0.0.1-SNAPSHOT-amd64

#      - name: Build Docker Image ARM64
#        run: ./gradlew bootBuildImage --imageName gamussa/apiops-workshop:0.0.1-SNAPSHOT-arm64

      - name: Push to Docker Hub
        run: docker push gamussa/apiops-workshop:0.0.1-SNAPSHOT-amd64 
        #&& docker push gamussa/apiops-workshop:0.0.1-SNAPSHOT-arm64

      - name: Create multiarch manifest
        run: docker manifest create gamussa/apiops-workshop:0.0.1-SNAPSHOT --amend gamussa/apiops-workshop:0.0.1-SNAPSHOT-amd64 
        #--amend gamussa/apiops-workshop:0.0.1-SNAPSHOT-arm64

      - name: Push Manifest to Docker Hub
        run: docker manifest push gamussa/apiops-workshop:0.0.1-SNAPSHOT
  